import React from "react";
import riseIcon from "../assets/images/rise.png";
import clockIcon from "../assets/images/clock.png";
import wifiIcon from "../assets/images/wifi-signal.png";
import menuIcon from "../assets/images/menu.png";
import downArrowIcon from "../assets/images/down-arrow.png";

function Navigation() {
  return (
      <nav
            style={{
                    display: "flex",
                            justifyContent: "space-between",
                                    alignItems: "center",
                                            padding: "12px 24px",
                                                    // borderBottom 없앰
                                                            flexWrap: "nowrap", 
                                                                    gap: "12px",
                                                                          }}
                                                                              >
                                                                                    <div style={{ display: "flex", gap: "24px", whiteSpace: "nowrap" }}>
                                                                                            <div style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                                                                                                      <img src={riseIcon} alt="Trending" style={{ width: "18px", height: "18px" }} />
                                                                                                                <span style={{ fontWeight: "bold", color: "#000" }}>트렌딩</span>
                                                                                                                        </div>
                                                                                                                                <div style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                                                                                                                                          <img
                                                                                                                                                      src={clockIcon}
                                                                                                                                                                  alt="Latest"
                                                                                                                                                                              style={{
                                                                                                                                                                                            width: "18px",
                                                                                                                                                                                                          height: "18px",
                                                                                                                                                                                                                        filter: "grayscale(100%) brightness(0) opacity(0.5)", 
                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                        <span style={{ color: "#888" }}>최신</span>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                        <div style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                              src={wifiIcon}
                                                                                                                                                                                                                                                                                                          alt="Feed"
                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                    width: "18px",
                                                                                                                                                                                                                                                                                                                                                  height: "18px",
                                                                                                                                                                                                                                                                                                                                                                filter: "grayscale(100%) brightness(0) opacity(0.5)", 
                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ color: "#888" }}>피드</span>
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: "flex", alignItems: "center", gap: "12px", whiteSpace: "nowrap" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gap: "4px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "6px 12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "4px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          whiteSpace: "nowrap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      minWidth: "80px", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  이번 주
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src={downArrowIcon} alt="Down arrow" style={{ width: "12px", height: "12px" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src={menuIcon} alt="Menu" style={{ width: "24px", height: "24px" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Navigation;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        